import {
  mdiAntenna,
  mdiAnvil,
  mdiBagPersonal,
  mdiBank,
  mdiBottleSodaClassic,
  mdiBottleWine,
  mdiBreadSlice,
  mdiCar,
  mdiCigar,
  mdiCodeBraces,
  mdiCog,
  mdiDiamondStone,
  mdiFactory,
  mdiFlask,
  mdiFoodDrumstick,
  mdiGasStation,
  mdiGlassWine,
  mdiHammerWrench,
  mdiHardHat,
  mdiHeartPulse,
  mdiHexagonMultiple,
  mdiLasso,
  mdiLaptop,
  mdiLightbulbOn,
  mdiMusicNote,
  mdiNeedle,
  mdiNewspaperVariant,
  mdiPalette,
  mdiPill,
  mdiPistol,
  mdiRug,
  mdiScaleBalance,
  mdiSchool,
  mdiSilverwareForkKnife,
  mdiSineWave,
  mdiSoccer,
  mdiSofa,
  mdiSprayBottle,
  mdiSprout,
  mdiStethoscope,
  mdiStore,
  mdiTextureBox,
  mdiTruckDelivery,
  mdiTshirtCrew,
  mdiWall,
} from "@mdi/js";

export const groupAccents = {
  science: "#9b3c32",
  technology: "#285f85",
  culture: "#704875",
  materials: "#746421",
  lifestyle: "#9a572f",
  food: "#36704b",
  commerce: "#8a610d",
  infrastructure: "#267177",
  knowledge: "#59488c",
  care: "#8d3c58",
} as const;

export type GroupName = keyof typeof groupAccents;

export type ClassMeta = {
  shortName: string;
  icon: string;
  group: GroupName;
};

export const classMeta: ClassMeta[] = [
  { shortName: "Chemicals", icon: mdiFlask, group: "science" },
  { shortName: "Paints", icon: mdiPalette, group: "science" },
  { shortName: "Cosmetics & cleaning", icon: mdiSprayBottle, group: "science" },
  { shortName: "Oils & fuels", icon: mdiGasStation, group: "science" },
  { shortName: "Pharmaceuticals", icon: mdiPill, group: "science" },
  { shortName: "Metal goods", icon: mdiAnvil, group: "technology" },
  { shortName: "Machinery", icon: mdiCog, group: "technology" },
  { shortName: "Hand tools", icon: mdiHammerWrench, group: "technology" },
  { shortName: "Tech & software", icon: mdiLaptop, group: "technology" },
  { shortName: "Medical devices", icon: mdiStethoscope, group: "technology" },
  { shortName: "Lighting & heating", icon: mdiLightbulbOn, group: "technology" },
  { shortName: "Vehicles", icon: mdiCar, group: "technology" },
  { shortName: "Firearms", icon: mdiPistol, group: "technology" },
  { shortName: "Jewelry", icon: mdiDiamondStone, group: "culture" },
  { shortName: "Musical instruments", icon: mdiMusicNote, group: "culture" },
  { shortName: "Paper goods", icon: mdiNewspaperVariant, group: "culture" },
  { shortName: "Rubber & plastics", icon: mdiHexagonMultiple, group: "materials" },
  { shortName: "Leather goods", icon: mdiBagPersonal, group: "materials" },
  { shortName: "Building materials", icon: mdiWall, group: "materials" },
  { shortName: "Furniture", icon: mdiSofa, group: "materials" },
  { shortName: "Housewares", icon: mdiGlassWine, group: "materials" },
  { shortName: "Ropes & fibers", icon: mdiLasso, group: "materials" },
  { shortName: "Yarns & threads", icon: mdiSineWave, group: "materials" },
  { shortName: "Textiles", icon: mdiTextureBox, group: "materials" },
  { shortName: "Clothing", icon: mdiTshirtCrew, group: "lifestyle" },
  { shortName: "Trims & fasteners", icon: mdiNeedle, group: "lifestyle" },
  { shortName: "Floor coverings", icon: mdiRug, group: "lifestyle" },
  { shortName: "Toys & sports", icon: mdiSoccer, group: "lifestyle" },
  { shortName: "Meat & dairy", icon: mdiFoodDrumstick, group: "food" },
  { shortName: "Staple foods", icon: mdiBreadSlice, group: "food" },
  { shortName: "Farm goods", icon: mdiSprout, group: "food" },
  { shortName: "Soft drinks", icon: mdiBottleSodaClassic, group: "food" },
  { shortName: "Alcoholic drinks", icon: mdiBottleWine, group: "food" },
  { shortName: "Tobacco", icon: mdiCigar, group: "food" },
  { shortName: "Business", icon: mdiStore, group: "commerce" },
  { shortName: "Finance", icon: mdiBank, group: "commerce" },
  { shortName: "Construction", icon: mdiHardHat, group: "infrastructure" },
  { shortName: "Telecoms", icon: mdiAntenna, group: "infrastructure" },
  { shortName: "Transport", icon: mdiTruckDelivery, group: "infrastructure" },
  { shortName: "Material treatment", icon: mdiFactory, group: "infrastructure" },
  { shortName: "Education & entertainment", icon: mdiSchool, group: "knowledge" },
  { shortName: "Science & tech", icon: mdiCodeBraces, group: "knowledge" },
  { shortName: "Food & lodging", icon: mdiSilverwareForkKnife, group: "care" },
  { shortName: "Health & beauty", icon: mdiHeartPulse, group: "care" },
  { shortName: "Legal & security", icon: mdiScaleBalance, group: "care" },
];
